<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>JUtilityPalette</AssemblyName>
    <RootNamespace>JUtility.App</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\JUtility.Core\JUtility.Core.csproj" />
  </ItemGroup>
</Project>
